## 1.2. Phyton scikit-learn library for machine learning

### Scikit-Learn Library

In [1]:
from sklearn.datasets import load_breast_cancer

In [2]:
type(load_breast_cancer())

sklearn.utils._bunch.Bunch

In [3]:
data=load_breast_cancer()

In [4]:
import pandas as pd

pd.DataFrame(data['data'])

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [5]:
pd.DataFrame(data['target'])

     0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [6]:
print(data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - class:
            - WDBC-Malignant
            - WDBC-Benign

:Summary Statistics:

===================================== ====== ======
                                        Min    Max
===================================== ====== ======
radius (mean):                        6.981  28.11
texture (mean):                       9.71   39.28
perimeter (mean):                     43.79  188.5
area (mean):                          143.5  2501.0
smoothness (mean):                    0.053  0.163
compactness (mean):                   0.019  0.345
concavity (mean):                     0.0    0.427
concave points (mean):                0.0    0.201
symmetry (mean):                      0.106  0.304
fractal dimension (mean):             0.05   0.097
radius (standard error):              0.112  2.873
texture (standard error):             0.36   4.885
perimeter (standard error):           0.757  21.98
area (standard error):                6.802  542.2
smoothness (standard error):          0.002  0.031
compactness (standard error):         0.002  0.135
concavity (standard error):           0.0    0.396
concave points (standard error):      0.0    0.053
symmetry (standard error):            0.008  0.079
fractal dimension (standard error):   0.001  0.03
radius (worst):                       7.93   36.04
texture (worst):                      12.02  49.54
perimeter (worst):                    50.41  251.2
area (worst):                         185.2  4254.0
smoothness (worst):                   0.071  0.223
compactness (worst):                  0.027  1.058
concavity (worst):                    0.0    1.252
concave points (worst):               0.0    0.291
symmetry (worst):                     0.156  0.664
fractal dimension (worst):            0.055  0.208
===================================== ====== ======

:Missing Attribute Values: None

:Class Distribution: 212 - Malignant, 357 - Benign

:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian

:Donor: Nick Street

:Date: November, 1995

This is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.
https://goo.gl/U2Uwz2

Features are computed from a digitized image of a fine needle
aspirate (FNA) of a breast mass.  They describe
characteristics of the cell nuclei present in the image.

Separating plane described above was obtained using
Multisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree
Construction Via Linear Programming." Proceedings of the 4th
Midwest Artificial Intelligence and Cognitive Science Society,
pp. 97-101, 1992], a classification method which uses linear
programming to construct a decision tree.  Relevant features
were selected using an exhaustive search in the space of 1-4
features and 1-3 separating planes.

The actual linear program used to obtain the separating plane
in the 3-dimensional space is that described in:
[K. P. Bennett and O. L. Mangasarian: "Robust Linear
Programming Discrimination of Two Linearly Inseparable Sets",
Optimization Methods and Software 1, 1992, 23-34].

This database is also available through the UW CS ftp server:

ftp ftp.cs.wisc.edu
cd math-prog/cpo-dataset/machine-learn/WDBC/

.. dropdown:: References

  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction
    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on
    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,
    San Jose, CA, 1993.
  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and
    prognosis via linear programming. Operations Research, 43(4), pages 570-577,
    July-August 1995.
  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques
    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)
    163-171.

In [7]:
from sklearn.model_selection import train_test_split

help(train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(
    *arrays,
    test_size=None,
    train_size=None,
    random_state=None,
    shuffle=True,
    stratify=None
)
    Split arrays or matrices into random train and test subsets.

    Quick utility that wraps input validation,
    ``next(ShuffleSplit().split(X, y))``, and application to input data
    into a single call for splitting (and optionally subsampling) data into a
    one-liner.

    Read more in the :ref:`User Guide <cross_validation>`.

    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.

    test_size : float or int, default=None
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to the
        complement of the train size. If ``train_size`` is also None, it will
        be set to 0.25.

    train_size : float or int, default=None
        If float, should be between 0.0 and 1.0 and represent the
        proportion of the dataset to include in the train split. If
        int, represents the absolute number of train samples. If None,
        the value is automatically set to the complement of the test size.

    random_state : int, RandomState instance or None, default=None
        Controls the shuffling applied to the data before applying the split.
        Pass an int for reproducible output across multiple function calls.
        See :term:`Glossary <random_state>`.

    shuffle : bool, default=True
        Whether or not to shuffle the data before splitting. If shuffle=False
        then stratify must be None.

    stratify : array-like, default=None
        If not None, data is split in a stratified fashion, using this as
        the class labels.
        Read more in the :ref:`User Guide <stratification>`.

    Returns
    -------
    splitting : list, length=2 * len(arrays)
        List containing train-test split of inputs.

        .. versionadded:: 0.16
            If the input is sparse, the output will be a
            ``scipy.sparse.csr_matrix``. Else, output type is the same as the
            input type.

    Examples
    --------
    >>> import numpy as np
    >>> from sklearn.model_selection import train_test_split
    >>> X, y = np.arange(10).reshape((5, 2)), range(5)
    >>> X
    array([[0, 1],
           [2, 3],
           [4, 5],
           [6, 7],
           [8, 9]])
    >>> list(y)
    [0, 1, 2, 3, 4]

    >>> X_train, X_test, y_train, y_test = train_test_split(
    ...     X, y, test_size=0.33, random_state=42)
    ...
    >>> X_train
    array([[4, 5],
           [0, 1],
           [6, 7]])
    >>> y_train
    [2, 0, 3]
    >>> X_test
    array([[2, 3],
           [8, 9]])
    >>> y_test
    [1, 4]

    >>> train_test_split(y, shuffle=False)
    [[0, 1, 2], [3, 4]]

In [8]:
len(data.data)

569

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target)

In [11]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

data=load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, random_state=42)

model = DecisionTreeClassifier(criterion='entropy')
model

DecisionTreeClassifier(criterion='entropy')

In [12]:
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [13]:
pred=model.predict(X_test)

In [14]:
pred_2d=pred.reshape(len(pred), 1)

In [15]:
pred_2d

array([[1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1]])

In [16]:
import numpy as np

In [17]:
y_test_2d=y_test.reshape(len(pred), 1)

In [18]:
df1=pd.DataFrame(pred_2d, columns=['pred'])

In [ ]:
df2=pd.DataFrame(y_test_2d, columns=['real'])

In [ ]:
pd.concat([df1, df2], axis=1)

In [ ]:
df_concat = pd.concat([df1, df2], axis=1)

In [ ]:
df_concat.columns

In [ ]:
df_concat[df_concat['pred'] == df_concat['real']]

In [ ]:
len(df_concat[df_concat['pred'] == df_concat['real']])

In [ ]:
137/143

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler()

In [ ]:
X_train

In [ ]:
df_scale_previous=pd.DataFrame(data['data'])

In [ ]:
scaler.fit(X_train)

In [ ]:
X_train=scaler.transform(X_train)

In [ ]:
df_scale_after=pd.DataFrame(X_train)

In [ ]:
df_scale_previous

In [ ]:
df_scale_after

In [ ]:
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target)

print(X_train)

scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)

X_train

In [ ]:
print(X_test)

X_test = scaler.fit_transform(X_test)

X_test

## 1.4. Data pre-processing for making a good training data set

### Missing value processing

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
iris=load_iris()

In [ ]:
import pandas as pd

In [ ]:
iris['data']

In [ ]:
iris_df = pd.DataFrame(iris['data'],
             columns=['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width'])

In [ ]:
iris_df.columns

In [ ]:
iris_df['Sepal_Length']

In [ ]:
import numpy as np

In [ ]:
np.mean(iris_df['Sepal_Length'])

In [ ]:
data=[[1.0,2.0,3.0,4.0],[5.0,6.0,np.nan,8.0],[10.0,11.0,12.0,np.nan]]

In [ ]:
np.array(data)

In [ ]:
pd.DataFrame(np.array(data), columns=['A','B','C','D'])

In [ ]:
df=pd.DataFrame(np.array(data), columns=['A','B','C','D'])

In [ ]:
df.isnull()

In [ ]:
df.isnull().sum()

In [ ]:
df.dropna()

In [ ]:
df.dropna(inplace=True)

In [ ]:
df

In [ ]:
df=pd.DataFrame(np.array(data), columns=['A','B','C','D'])

In [ ]:
df

In [ ]:
df.dropna(axis=1, inplace=True)

In [ ]:
df

In [ ]:
df=pd.DataFrame(np.array(data), columns=['A','B','C','D'])

In [ ]:
df

In [ ]:
df.loc[3]=[np.nan,np.nan,np.nan,np.nan]

In [ ]:
df

In [ ]:
df.dropna(how='all', inplace=True)

In [ ]:
df

In [ ]:
df=pd.DataFrame(np.array(data), columns=['A','B','C','D'])
df.loc[3]=[np.nan,np.nan,np.nan,3]

In [ ]:
df

In [ ]:
df.dropna(thresh=3, inplace=True)

In [ ]:
df

In [ ]:
df

In [ ]:
df.dropna(subset=['C'], inplace=True)

In [ ]:
df

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
df=pd.DataFrame(np.array(data), columns=['A','B','C','D'])

In [ ]:
impt=SimpleImputer(missing_values=np.nan, strategy='mean')

In [ ]:
df.values

In [ ]:
help(impt.fit)

In [ ]:
imputed=impt.fit(df.values)

In [ ]:
imputed.transform(df.values)

In [ ]:
(3+12)/2

In [ ]:
df = pd.DataFrame([['green', 'M', 10.1, 'class2'],
                   ['red', 'L', 13.5, 'class1'],
                   ['blue', 'XL', 15.3, 'class2']])

In [ ]:
df

In [ ]:
size_mapping = {'XL': 3,
                'L': 2,
                'M': 1}

In [ ]:
df.columns=['color', 'size', 'price', 'classlabel']

In [ ]:
df

In [ ]:
df['size']

In [ ]:
df['size']=df['size'].map(size_mapping)

In [ ]:
df['size']

In [ ]:
df

In [ ]:
df['classlabel']

In [ ]:
df['classlabel'].value_counts()

In [ ]:
np.unique(df['classlabel'])

In [ ]:
enumerate(np.unique(df['classlabel']))

In [ ]:
for idx, label in enumerate(np.unique(df['classlabel'])):
    print(idx, label)

In [ ]:
{label: idx for idx, label in enumerate(np.unique(df['classlabel']))}

In [ ]:
class_mapping={label: idx for idx, label in enumerate(np.unique(df['classlabel']))}

In [ ]:
df['classlabel']=df['classlabel'].map(class_mapping)
df

In [ ]:
df = pd.DataFrame([['green', 'M', 10.1, 'class2'],
                   ['red', 'L', 13.5, 'class1'],
                   ['blue', 'XL', 15.3, 'class2']])
df.columns=['color', 'size', 'price', 'classlabel']

In [ ]:
df

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
enc=LabelEncoder()

In [ ]:
y=enc.fit_transform(df['classlabel'].values)

In [ ]:
y

In [ ]:
iris.target

In [ ]:
iris=pd.DataFrame(iris.target, columns=['species'])

In [ ]:
iris

In [ ]:
iris['species'] = iris['species'].replace({0:'setosa', 1:'versicolor', 2:'virginica'})

In [ ]:
iris

In [ ]:
pd.get_dummies(iris['species'])

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
onehot_encoder=OneHotEncoder()

In [ ]:
len_iris=len(iris['species'])

In [ ]:
np.array(iris['species'])

In [ ]:
iris_species_2d=np.array(iris['species']).reshape(len_iris, 1)

In [ ]:
onehot_encoder.fit_transform(iris_species_2d)

In [ ]:
#Convert to a space matrix

In [ ]:
onehot_reshaped=onehot_encoder.fit_transform(iris_species_2d)

In [ ]:
print(onehot_reshaped[0:50])

In [ ]:
print(onehot_reshaped[50:100])

In [ ]:
print(onehot_reshaped[100:150])

In [ ]:
df_wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',
                      header=None)

df_wine.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash',
                   'Alcalinity of ash', 'Magnesium', 'Total phenols',
                   'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
                   'Color intensity', 'Hue', 'OD280/OD315 of diluted wines',
                   'Proline']

print('Class labels', np.unique(df_wine['Class label']))
df_wine.head()

In [ ]:
from sklearn.model_selection import train_test_split

X, y = df_wine.iloc[:, 1:].values, df_wine.iloc[:, 0].values

X_train, X_test, y_train, y_test =\
    train_test_split(X, y,
                    test_size=0.3,
                    random_state=0,
                    stratify=y)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()
X_train_norm = mms.fit_transform(X_train)
X_test_nrom = mms.transform(X_test)

In [ ]:
from sklearn.preprocessing import StandardScaler

stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

In [ ]:
from sklearn.preprocessing import RobustScaler
rbs = RobustScaler()
X_train_robust = rbs.fit_transform(X_train)
X_test_robust = rbs.transform(X_test)

In [ ]:
# MaxAbsScaler divides the data into the maximum absolute value based on each feature.
# Thus, the maximum value of each feature becomes 1.
# The overall feature changes to [-1, 1] range.

In [ ]:
from sklearn.preprocessing import MaxAbsScaler
mas = MaxAbsScaler()
X_train_maxabs = mas.fit_transform(X_train)
X_test_maxabs = mas.transform(X_test)

## 1.5. Practicing to find an optimal method to solve problems with scikit-learn

In [ ]:
from sklearn.datasets import load_iris
data=load_iris()
data.keys()

In [ ]:
print(data.DESCR)

In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
iris=pd.DataFrame(data=data.data, columns=data.feature_names)
iris

In [ ]:
feature=pd.DataFrame(data=data.data, columns=data.feature_names)

In [ ]:
data.target

In [ ]:
target=pd.DataFrame(data.target, columns=["species"])

In [ ]:
target

In [ ]:
iris = pd.concat([feature, target], axis=1)

iris.rename({"sepal length (cm)":"sepal_length", "sepal width (cm)":"sepal_width",
             "petal length (cm)":"petal_length", "petal width (cm)":"petal_width"},
            axis=1, inplace=True)
iris.columns

In [ ]:
iris["species"]=iris.species.map(lambda x: data.target_names[x])
iris.head()

In [ ]:
iris.isna().sum()

In [ ]:
iris.info()

In [ ]:
iris.describe()

In [ ]:
iris.corr(numeric_only=True)

In [ ]:
iris.groupby('species').size()

In [ ]:
def boxplot_iris(feature_names, dataset):
    i=1
    plt.figure(figsize=(11,9))
    for col in feature_names:
        plt.subplot(2,2,i)
        plt.axis('on')
        plt.tick_params(axis='both', left=True,
                        top=False, right=False,
                        bottom=True, labelleft=False,
                        labeltop=False, labelright=False,
                        labelbottom=False)
        dataset[col].plot(kind='box', subplots=True, sharex=False)
        plt.title(col)
        i += 1
    plt.show()

In [ ]:
boxplot_iris(iris.columns[:-1], iris)

In [ ]:
def histogram_iris(feature_names, dataset):
    i=1
    plt.figure(figsize=(11,2))
    for col in feature_names:
        plt.subplot(1,4,i)
        plt.axis('on')
        plt.tick_params(axis='both', left=True,
                        top=False, right=False,
                        bottom=True, labelleft=False,
                        labeltop=False, labelright=False,
                        labelbottom=False)
        dataset[col].plot(kind='hist', subplots=True, grid=True)
        plt.title(col)
        i += 1
    plt.show()

In [ ]:
histogram_iris(iris.columns[:-1], iris)

In [ ]:
corr=iris.corr(numeric_only=True)
cmap=sns.diverging_palette(220,20, as_cmap=True)
plt.figure(figsize=(11,9))
sns.heatmap(corr, cmap=cmap, vmax=1.0, vmin=-1.0, center=0, square=True,
            linewidths=.5, cbar_kws={"shrink":.5})
plt.show()

In [ ]:
sns.pairplot(iris, hue="species")
plt.plot()

In [ ]:
def piechar_iris(feature_names, target, dataset):
    i=1
    plt.figure(figsize=(11,9))
    for colName in [target]:
        labels=[];sizes=[];
        df=dataset.groupby(colName).size()
        for key in df.keys():
            labels.append(key)
            sizes.append(df[key])
        plt.subplot(2,2,i)
        plt.axis('on')
        plt.tick_params(axis='both', left=True,
                        top=False, right=False,
                        bottom=True, labelleft=True,
                        labeltop=True, labelright=False,
                        labelbottom=False)
        plt.pie(sizes, labels=labels, autopct='%1.1f%%',
                shadow=True, startangle=140)
        plt.axis('equal')
        i += 1
    plt.show()

In [ ]:
piechar_iris(iris.columns[:-1], iris.species, iris)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test=train_test_split(iris.iloc[:,:-1], iris.iloc[:,-1],
                                                  test_size=0.33, random_state=42)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
model = DecisionTreeClassifier(criterion='gini',splitter='best',max_depth=None,min_samples_split=2,
                               min_samples_leaf=1,min_weight_fraction_leaf=0.0,max_features=None,
                               random_state=42,max_leaf_nodes=None,min_impurity_decrease=0.0,
                               class_weight=None)

In [ ]:
model.fit(X_train, y_train)

In [ ]:
model.score(X_test, y_test)

In [ ]:
import numpy as np
from sklearn.model_selection import cross_val_score, KFold
cv=KFold(n_splits=10,shuffle=True,random_state=42)
results=cross_val_score(model, X_train, y_train, cv=cv)
fin_result=np.mean(results)

In [ ]:
for i, score in enumerate(results):
    print(f"{i}th cross validation score: {score}")
print(f"\ncross validation final score: {fin_result}")

In [ ]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold(n_splits=10,shuffle=True,random_state=42)
results=cross_val_score(model, X_train, y_train, cv=cv)
fin_result=np.mean(results)
for i, score in enumerate(results):
    print(f"{i}th cross validation score: {score}")

In [ ]:
print(f"cross validation final score: {fin_result}")

In [ ]:
!pip install scikit-plot

In [ ]:
import numpy as np
import scipy
scipy.interp = np.interp
import scikitplot as skplt

In [ ]:
import matplotlib.pyplot as plt
skplt.estimators.plot_learning_curve(model,
                                     X_train, y_train,
                                     figsize=(6,6))
plt.show()

In [ ]:
estimator=DecisionTreeClassifier()
from sklearn.model_selection import GridSearchCV
parameters={'max_depth': [4,6,8,10,12],
            'criterion': ['gini', 'entropy'],
            'splitter': ['best', 'random'],
            'min_weight_fraction_leaf': [0.0,0.1,0.2,0.3],
            'random_state': [7,23,42,78,142],
            'min_impurity_decrease': [0.0,0.05,0.1,0.2]}
model2=GridSearchCV(estimator=estimator,
                    param_grid=parameters,
                    cv=KFold(10), verbose=1,
                    n_jobs=-1, refit=True)
model2.fit(X_train, y_train)

In [ ]:
model2.best_estimator_

In [ ]:
model2.best_params_

In [ ]:
model2.best_score_

In [ ]:
from sklearn.metrics import accuracy_score
pred=model2.predict(X_test)
pred[:20]

In [ ]:
accuracy_score(y_test, pred)

In [ ]:
from sklearn.metrics import confusion_matrix
pred=model2.predict(X_test)
confusion_matrix(y_test, pred)

In [ ]:
import scikitplot as skplt
skplt.metrics.plot_confusion_matrix(y_test, pred, figsize=(8,6))
plt.show()

In [ ]:
from sklearn.metrics import precision_score
precisions=precision_score(y_test, pred, average=None)

for target, score in zip(data.target_names, precisions):
    print(f"{target} precision: {score}")

In [ ]:
from sklearn.metrics import recall_score
recalls=recall_score(y_test, pred, average=None)
for target, score in zip(data.target_names, recalls):
    print(f"{target} sensitivity: {score}")

In [ ]:
from sklearn.metrics import fbeta_score, f1_score

fbetas=fbeta_score(y_test, pred, beta=1, average=None)

for target, score in zip(data.target_names, fbetas):
    print(f"{target} fbetas score: {score}")

f1s=f1_score(y_test, pred, average=None)

for target, score in zip(data.target_names, f1s):
    print(f"{target} f1 score: {score}")

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

In [ ]:
pred_proba=model2.predict_proba(X_test)

In [ ]:
pred_proba

In [ ]:
import scikitplot as skplt
skplt.metrics.plot_roc(y_test, pred_proba, figsize=(8,6))
plt.show()

In [ ]:
model.fit(iris.iloc[:,:-1], iris.iloc[:,-1])

In [ ]:
import pickle

In [ ]:
with open('final_model.pickle', 'wb') as fp:
    pickle.dump(model2, fp)

In [ ]:
f=open('final_model.pickle', 'rb')
model3=pickle.load(f)

In [ ]:
predicted_species=model3.predict(iris.iloc[:,:-1])

In [ ]:
iris['predicted_species']=predicted_species
iris.to_csv('FinalResult.csv', index=False)